--- #YAML:1.0
name:               Sew-Color
version:            1.03
abstract:           Perl Module for giving rgb values for colours of varous manufactures embroidery thread
author:
    - mark winder <markwin@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
